CREATE TABLE IF NOT EXISTS notes (
  id CHARACTER(36) NOT NULL PRIMARY KEY,
  title VARCHAR(60),
  text VARCHAR(512),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TRIGGER IF NOT EXISTS UpdateTimestamps AFTER UPDATE ON notes
  FOR EACH ROW WHEN NEW.updated_at <= OLD.updated_at
BEGIN
  update notes set updated_at=CURRENT_TIMESTAMP where id=OLD.id;
END;

